version: '3.4'

services:
  catalogdb:
    container_name: mongo-shop
    restart: always
    volumes:
      - mongo-shop-data:/data/db
    ports:
      - "27017:27017"
  basketdb:
    container_name: redis-shop
    restart: always
    ports:
      - "6379:6379"
 
  discountdb:
    container_name: postgres-shop
    restart: always
    environment:
      POSTGRES_DB: DiscountDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Abc12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-shop-data:/var/lib/postgresql/data
 
  pgadmin:
    container_name: pgadmin4-shop
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: Abc12345
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin4-shop-data:/var/lib/pgadmin'

  portainer:
    container_name: portainer-shop
    restart: always
    ports:
      - "9000:9000"
    volumes:
        - portainer-shop-data:/data
        - /var/run/docker.sock:/var/run/docker.sock

  catalog.api:
    container_name: catalog.api.v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Database__ConnectionString=mongodb://mongo-shop:27017"
    depends_on: 
      - catalogdb
    ports:
      - "5000:80"

  basket.api:
    container_name: basket.api.v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Cache__ConnectionString=redis-shop:6379"
    depends_on: 
      - basketdb
    ports:
      - "5001:80"

  discount.api:
    container_name: discount.api.v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Default=User ID=admin;Password=Abc12345;Host=discountdb;Port=5432;Database=DiscountDB"
    depends_on: 
      - discountdb
    ports:
      - "5002:80"

volumes:
  mongo-shop-data:
  portainer-shop-data:
  postgres-shop-data:
  pgadmin4-shop-data: