version: '3.4'

services:
  catalogdb:
    image:  mongo
    container_name: mongo-shop
    restart: always
    volumes:
      - mongo-shop-data:/data/db
    ports:
      - "27017:27017"
  basketdb:
    image: redis
    container_name: redis-shop
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api.v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Database__ConnectionString=mongodb://mongo-shop:27017"
      - "ASPNETCORE_URLS=http://+:80"
    depends_on: 
      - catalogdb
    ports:
      - "5000:80"

  basket.api:
    container_name: basket.api.v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Cache__ConnectionString=redis-shop:6379"
      - "ASPNETCORE_URLS=http://+:80"
    depends_on: 
      - basketdb
    ports:
      - "5001:80"

volumes:
 mongo-shop-data:

 